stages:

- stage: Build
  jobs:

  - job: Linux
    pool:
      vmImage: ubuntu-latest
    container:
      image: offshoregfw/centos-build:latest
    steps:
    - script: |
        set -euo pipefail
        echo 'target_link_libraries(offshore dl)' >> CMakeLists.txt
        cmake -DMYSQL_INCLUDE_DIR=/usr/local/include/mariadb -DMYSQL_LIBRARY=/usr/local/lib/mariadb/libmysqlclient.a -DDEFAULT_CONFIG=config.json -DFORCE_TCP_FASTOPEN=ON -DBoost_USE_STATIC_LIBS=ON .
        make
        strip -s offshore
    - publish: $(System.DefaultWorkingDirectory)/offshore
      artifact: LinuxBinary

  - job: macOS
    pool:
      vmImage: macOS-latest
    steps:
    - script: |
        set -euo pipefail
        brew install boost openssl@1.1
        cmake -DBoost_USE_STATIC_LIBS=ON -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@1.1/include -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl@1.1/lib/libcrypto.a -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl@1.1/lib/libssl.a -DDEFAULT_CONFIG=config.json -DENABLE_MYSQL=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 .
        make
        strip -SXTx offshore
    - publish: $(System.DefaultWorkingDirectory)/offshore
      artifact: macOSBinary

  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
    - bash: |
        set -euo pipefail
        curl -LO https://slproweb.com/download/Win64OpenSSL-1_1_1h.exe
        powershell ".\\Win64OpenSSL-1_1_1h.exe /silent /sp- /suppressmsgboxes /DIR='C:\\Program Files\\OpenSSL-Win64'"
        cmake -DBoost_INCLUDE_DIR="${BOOST_ROOT_1_72_0}/include" -DBoost_USE_STATIC_LIBS=ON -DOPENSSL_ROOT_DIR='C:/Program Files/OpenSSL-Win64' -DOPENSSL_USE_STATIC_LIBS=ON -DENABLE_MYSQL=OFF .
        cmake --build . --config Release
    - publish: $(System.DefaultWorkingDirectory)/Release/offshore.exe
      artifact: WindowsBinary

- stage: Test
  jobs:

  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: LinuxBinary
    - script: |
        set -uo pipefail
        BINARY="$PIPELINE_WORKSPACE/LinuxBinary/offshore"
        chmod +x "$BINARY"
        mkdir results
        cp -r "$(tests/LinuxSmokeTest/basic.sh "$BINARY")" results/basic
        cp -r "$(tests/LinuxSmokeTest/fake-client.sh "$BINARY")" results/fake-client
      env:
        PIPELINE_WORKSPACE: $(Pipeline.Workspace)
    - publish: $(System.DefaultWorkingDirectory)/results
      artifact: LinuxTest

- stage: Package
  jobs:

  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
    - download: current
      artifact: LinuxBinary
    - script: |
        set -euo pipefail
        BINARY="$PIPELINE_WORKSPACE/LinuxBinary/offshore"
        chmod +x "$BINARY"
        mkdir offshore
        cp "$BINARY" offshore/offshore
        cp -r examples CONTRIBUTORS.md LICENSE README.md offshore
        cp examples/server.json-example offshore/config.json
        tar cf offshore-linux-amd64.tar offshore
        xz offshore-linux-amd64.tar
      env:
        PIPELINE_WORKSPACE: $(Pipeline.Workspace)
    - publish: $(System.DefaultWorkingDirectory)/offshore-linux-amd64.tar.xz
      artifact: LinuxRelease

  - job: macOS
    pool:
      vmImage: macOS-latest
    steps:
    - download: current
      artifact: macOSBinary
    - script: |
        set -euo pipefail
        BINARY="$PIPELINE_WORKSPACE/macOSBinary/offshore"
        chmod +x "$BINARY"
        mkdir offshore
        cp "$BINARY" offshore/offshore
        cp -r examples CONTRIBUTORS.md LICENSE README.md offshore
        cp examples/client.json-example offshore/config.json
        rm offshore/examples/nat.json-example offshore/examples/offshore.service-example
        cat > offshore/start.command <<EOF
        #!/bin/sh

        cd "\$(dirname "\$0")"
        ./offshore
        EOF
        chmod +x offshore/start.command
        zip -r9 offshore-macos.zip offshore
      env:
        PIPELINE_WORKSPACE: $(Pipeline.Workspace)
    - publish: $(System.DefaultWorkingDirectory)/offshore-macos.zip
      artifact: macOSRelease

  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
    - download: current
      artifact: WindowsBinary
    - bash: |
        set -euo pipefail
        BINARY="$PIPELINE_WORKSPACE/WindowsBinary/offshore.exe"
        mkdir offshore
        cp "$BINARY" offshore/offshore.exe
        cp -r examples CONTRIBUTORS.md LICENSE README.md offshore
        cp examples/client.json-example offshore/config.json
        rm offshore/examples/nat.json-example offshore/examples/offshore.service-example
        7z a -mx=9 offshore-win.zip offshore
      env:
        PIPELINE_WORKSPACE: $(Pipeline.Workspace)
    - publish: $(System.DefaultWorkingDirectory)/offshore-win.zip
      artifact: WindowsRelease
